package com.rest.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Carro implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CARRO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "CARRO_ID_SEQ", name = "CARRO_ID_GENERATOR")
	private Long id;

	@org.kie.api.definition.type.Label("Marca")
	private String marca;

	@org.kie.api.definition.type.Label("Nome")
	private String nome;

	@org.kie.api.definition.type.Label("Preço (R$)")
	private Double preco;

	@org.kie.api.definition.type.Label("Potência (cv)")
	private Integer potencia;

	@org.kie.api.definition.type.Label(value = "Tipo de Carro")
	private java.lang.String tipocarro;

	public Carro() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getMarca() {
		return this.marca;
	}

	public void setMarca(java.lang.String marca) {
		this.marca = marca;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.Double getPreco() {
		return this.preco;
	}

	public void setPreco(java.lang.Double preco) {
		this.preco = preco;
	}

	public java.lang.Integer getPotencia() {
		return this.potencia;
	}

	public void setPotencia(java.lang.Integer potencia) {
		this.potencia = potencia;
	}

	public java.lang.String getTipocarro() {
		return this.tipocarro;
	}

	public void setTipocarro(java.lang.String tipocarro) {
		this.tipocarro = tipocarro;
	}

	public Carro(java.lang.Long id, java.lang.String marca,
			java.lang.String nome, java.lang.Double preco,
			java.lang.Integer potencia, java.lang.String tipocarro) {
		this.id = id;
		this.marca = marca;
		this.nome = nome;
		this.preco = preco;
		this.potencia = potencia;
		this.tipocarro = tipocarro;
	}

}